### ISSUE TITLE
About inference speed?

### ISSUE THREAD

**Issue by xiao2mo** [nttcslab/byol-a#14]
Hi is there any inference speed evaluation?
And how to deal with  long audios in production?
Many thanks for ur great work.

**Comment by daisukelab** [comment]
Hello @xiao2mo, thank you for your interest!
We're sorry that we don't have evaluated inference speed.
As you would understand, this work is learning general-purpose representation, which we think is a basic part of research rather than proceeding to the matured stage of production.
To bring this work up to the level of production, I think we have many things to discuss, including how long to handle the input audio.
Then let me expect, please try with your purpose and share your problem, and hopefully with a new paper that proposes solutions for the problem! :)

**Comment by daisukelab** [comment]
Closing for now, please reopen if you need more assistance.
